export const CLEAR_CANVAS = 'CLEAR_CANVAS';
export const FILL_CANVAS = 'FILL_CANVAS';
export const SWITCH_PAINTING_COLOR = 'SWITCH_PAINTING_COLOR';
export const SWITCH_PAINT_TOOL = 'SWITCH_PAINT_TOOL';
